-- 운동부 TABLE
-- TEAM : 팀 아이디, 지역, 팀 명, 개설 날짜, 전화번호, 홈페이지
CREATE TABLE TEAM(      
    TEAM_ID VARCHAR2(20), -- 기본키
    TEAM_CITY VARCHAR2(20),
    TEAM_NAME VARCHAR2(20),
    TEAM_DATE VARCHAR2(30),
    TEAM_PHON VARCHAR2(20),
    TEAM_HPG VARCHAR2(20),
    CONSTRAINT PK_TEAM_ID PRIMARY KEY(TEAM_ID)
);

INSERT INTO TEAM(TEAM_ID, TEAM_CITY, TEAM_NAME, TEAM_DATE,TEAM_PHON, TEAM_HPG)
VALUES('축구부', '서울', '서울FC', '1997-03-10', '02-123-456', 'WWW.Seoul.com');


INSERT INTO TEAM(TEAM_ID, TEAM_CITY, TEAM_NAME, TEAM_DATE,TEAM_PHON, TEAM_HPG)
VALUES('야구부', '대구', '대구FC', '2021-09-15', '053-123-456', 'WWW.Daegu.com');

-- PLAYER : 선수번호, 선수 명, 등록일, 포지션, 키, 팀 아이디
CREATE TABLE PLAYER(      
    PLAYER_NUM NUMBER, -- 기본키
    PLAYER_NAME VARCHAR2(15),
    PLAYER_DATE VARCHAR2(20),
    PLAYER_POS VARCHAR2(15),
    PLAYER_HEI NUMBER,
    TEAM_ID VARCHAR2(20),
    CONSTRAINT FK_PLAYER FOREIGN KEY(TEAM_ID)
    REFERENCES TEAM(TEAM_ID) -- 참조
);

-- 팀 추가
INSERT INTO PLAYER(PLAYER_NUM, PLAYER_NAME,PLAYER_DATE, PLAYER_POS, PLAYER_HEI, TEAM_ID)
VALUES(10, '손흥민', '2020-09-15', '공격수', '180.3', '축구부');


INSERT INTO PLAYER(PLAYER_NUM, PLAYER_NAME,PLAYER_DATE, PLAYER_POS, PLAYER_HEI, TEAM_ID)
VALUES(99, '류현진', '2020-07-07', '투수', '183.3', '야구부');

SELECT t.team_name, t.team_phon, t.team_hpg
FROM team t, player p
WHERE t.team_id = p.team_id
AND PLAYER_NAME = '손흥민';


-- 온라인 마켓 TABLE
-- PRODUCT(상품) : 상품번호, 상품명, 상품가격, 상품설명
CREATE TABLE PRODUCT(      
    PRODUCT_NUM NUMBER, -- 기본키
    PRODUCT_NAME VARCHAR2(20),
    PRODUCT_PRICE NUMBER,
    PRODUCT_EX VARCHAR2(30),
    CONSTRAINT PK_PRODUCT_NUM PRIMARY KEY(PRODUCT_NUM) -- PRODUCT_NUM NUMBER PRIMARY KEY
);

INSERT INTO PRODUCT(PRODUCT_NUM, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_EX)
VALUES(101, '티셔츠', 30000, '검은색 맨투맨');

INSERT INTO PRODUCT(PRODUCT_NUM, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_EX)
VALUES(102, '바지', 50000, '연청바지');

INSERT INTO PRODUCT(PRODUCT_NUM, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_EX)
VALUES(103, '아우터', 100000, '트렌치코트');



-- CONSUMER(소비자) : 소비자 ID, 이름, 나이
CREATE TABLE CONSUMER(      
    CONSUMER_ID VARCHAR2(20), -- 기본키
    CONSUMER_NAME VARCHAR2(20),
    CONSUMER_AGE NUMBER,
    CONSTRAINT PK_CONSUMER_AGE PRIMARY KEY(CONSUMER_ID)
);

INSERT INTO CONSUMER(CONSUMER_ID,CONSUMER_NAME, CONSUMER_AGE)
VALUES('HONG', '홍길동', 25);

INSERT INTO CONSUMER(CONSUMER_ID,CONSUMER_NAME, CONSUMER_AGE)
VALUES('JJANG', '짱구', 27);

INSERT INTO CONSUMER(CONSUMER_ID,CONSUMER_NAME, CONSUMER_AGE)
VALUES('HUN', '훈이', 30);

-- CART(장바구니) : 장바구니 번호, 소비자 ID, 상품번호, 수량
CREATE TABLE CART(      
    CART_NUM NUMBER, -- 기본키
    CONSUMER_ID VARCHAR2(20),
    PRODUCT_NUM NUMBER,
    CART_COUNT NUMBER,
    CONSTRAINT FK_CART FOREIGN KEY(CONSUMER_ID)
    REFERENCES CONSUMER(CONSUMER_ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY(PRODUCT_NUM)
    REFERENCES PRODUCT(PRODUCT_NUM)
);

INSERT INTO CART(CART_NUM,CONSUMER_ID, PRODUCT_NUM, CART_COUNT)
VALUES(1, 'HONG', 101, 3);

INSERT INTO CART(CART_NUM,CONSUMER_ID, PRODUCT_NUM, CART_COUNT)
VALUES(2, 'JJANG', 102, 5);

INSERT INTO CART(CART_NUM,CONSUMER_ID, PRODUCT_NUM, CART_COUNT)
VALUES(3, 'HUN', 103, 7);

SELECT * 
FROM product p, consumer c, cart ca
WHERE p.product_num = ca.product_num
    AND c.consumer_id = ca.consumer_id
        AND c.consumer_name = '짱구';



